<?php

define( 'TW_ACCOUNT_SID', 'INSERT YOUR ACCOUNT SID');
define( 'TW_SECRET_KEY', 'INSERT YOUR SECRET KEY');

define( 'AWS_ACCESS_KEY', 'INSERT YOUR ACCESS KEY');
define( 'AWS_SECRET_KEY', 'INSERT YOUR SECRET KEY');
define( 'S3_BUCKET_NAME', 'INSERT YOUR BUCKET NAME');

?>